defaults:
  - optimizer: adam
  - lr_scheduler: step_lr
  # - lr_scheduler: none
  - dataset: constantcount_dhp19
  - loss: multipixelwise
  - augmentation: no_aug
  - training: margipose
  - hydra: standard
  - hydra/help: help
  # - _self_

gpus: [0]
epochs: 100
early_stopping: 10
batch_size: 32
num_workers: 16
train_val_split: 0.8

debug: false
root_dir: C:/code/EventHPE/result/8.26/exps
model_zoo: C:/code/EventHPE/result/8.26/model_zoo
project_name: event_hpe
resume: false
result_file: results.json 
load_path:
accelerator: ddp

